name: q_officer_barantin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl_phone_field: ^3.2.0
  sqflite: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider_android: ^2.2.0
  image_picker: ^1.0.0
  dotted_border: ^2.0.0
  shimmer: ^3.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  geocoding: ^3.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.14
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^17.0.0
  custom_info_window: ^1.0.1
  uuid: ^4.5.1
  convert: ^3.1.2
  permission_handler: ^12.0.0+1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  tutorial_coach_mark: ^1.2.9
  smooth_page_indicator: ^1.1.0
  flutter_image_compress: ^2.4.0
  html: ^0.15.6
  mobile_scanner: ^7.0.1
  image: ^4.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: "images/logo_apk.png"

flutter:
  uses-material-design: true

  assets:
    - images/logo_barantin.png
    - images/best_trust.png
    - images/plus_icon.png
    - images/pk_icon.png
    - images/not_found.png
    - images/logo_apk.png
    - images/icon_qdc.png
    - dataUPT/master_upt.htm

fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter_18pt-Regular.ttf
      - asset: fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_24pt-Regular.ttf
      - asset: fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_28pt-Regular.ttf
      - asset: fonts/Inter_28pt-Bold.ttf
        weight: 700

  - family: Urbanist
    fonts:
      - asset: fonts/Urbanist-BlackItalic.ttf
        weight: 900

