name: q_officer_barantin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl_phone_field: ^3.2.0
  sqflite: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider_android: ^2.2.0
  image_picker: ^1.0.0
  dotted_border: ^2.0.0
  shimmer: ^3.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  geocoding: ^3.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.14
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^17.0.0
  custom_info_window: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo_barantin.png
    - images/best_trust.png
    - images/plus_icon.png
    - images/pk_icon.png
    - images/not_found.png

fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter_18pt-Regular.ttf
      - asset: fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_24pt-Regular.ttf
      - asset: fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_28pt-Regular.ttf
      - asset: fonts/Inter_28pt-Bold.ttf
        weight: 700
