// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7KcRYIUXuFuudyu_dunHlCsbt2kyARY',
    appId: '1:739593394787:web:a33c32ca0cb424e95f3656',
    messagingSenderId: '739593394787',
    projectId: 'e-officer',
    authDomain: 'e-officer.firebaseapp.com',
    storageBucket: 'e-officer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCINmiQjXPmJ1p3UGy2MB5g8-JAl6C0G0',
    appId: '1:739593394787:android:9bb81fa6681b658e5f3656',
    messagingSenderId: '739593394787',
    projectId: 'e-officer',
    storageBucket: 'e-officer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0opYVyOZFs5m0RYUSekmzFp9dGuRPAQ',
    appId: '1:739593394787:ios:e056c036b2cb2ab85f3656',
    messagingSenderId: '739593394787',
    projectId: 'e-officer',
    storageBucket: 'e-officer.firebasestorage.app',
    iosBundleId: 'com.example.eOfficer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0opYVyOZFs5m0RYUSekmzFp9dGuRPAQ',
    appId: '1:739593394787:ios:e056c036b2cb2ab85f3656',
    messagingSenderId: '739593394787',
    projectId: 'e-officer',
    storageBucket: 'e-officer.firebasestorage.app',
    iosBundleId: 'com.example.eOfficer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh7KcRYIUXuFuudyu_dunHlCsbt2kyARY',
    appId: '1:739593394787:web:89c7b730976a4c855f3656',
    messagingSenderId: '739593394787',
    projectId: 'e-officer',
    authDomain: 'e-officer.firebaseapp.com',
    storageBucket: 'e-officer.firebasestorage.app',
  );
}
